### ISSUE TITLE
Command not found error

### ISSUE THREAD

**Issue by ddurgaprasad** [treigerm/WaterNet#6]
Thanks for sharing the tool.I get the below error after running the below command
$ docker build -t water_net .

```
$ cd WaterNet-master/
$clear
$ls
Dockerfile		README.md		waterNet
LICENSE			requirements.txt	waterNet.py
$waterNet -h
-bash: waterNet: command not found
$
```

**Comment by treigerm** [comment]
You will have to build the Docker image first and then run the command inside a running container. Infos on how to do that are in the Readme.

**Comment by ddurgaprasad** [comment]
I think Docker is troublesome on Windows 10 . I have moved on with and trying to work the sample using normal python console.
